### PR TITLE
Exit code: set exit code whether you call Sauce Labs or not

### PR DESCRIPTION
**Pull request by rrees**
Following on from conversation with @theefer @cutandpastey and @hmgibson23 I've changed the code to call process exit whether we call SauceLabs or not.

I've tried to test this locally by npm linking and it seems to not die in a fire.

### CODE REVIEW

**Comment by hmgibson23** [comment]
:+1:

**Comment by cutandpastey** [comment]
Hold on, I don't think this acts as expected.  The `mocha.run` callback is fired only if mocha completes.  If theres a timeout mocha doesn't complete and is left hanging and as such the callback doesn't fire.

So if the intention is to exit with code 1 if you can't connect to Sauce Labs this is all good, but i think that this is all this does, unless i'm missing something?

**Comment by rrees** [comment]
@cutandpastey Yes it is just fixing that issue initially, not the timeout one. In the timeout case you shouldn't need to check the failed tests you can just exit immediately with an error status

**Comment by cutandpastey** [comment]
What you can do is:

``` js
var runner = createRunner(mocha);
runner.on('fail', function(suite, err){
    //check err is because of a timeout if so do the below
    process.exit(1);
})
```

**Comment by cutandpastey** [comment]
Oh okay, well the above should help you with your timeouts anyways :)

**Comment by rrees** [comment]
@cutandpastey For part two

**Comment by theefer** [comment]
:+1: 

For part 2, would be best to have all "exit(1) on fail" logic inside this test harness helper, rather than spreading it both in here and in the calling runner.js.

**Pull request merged**
